default_agent: lineshopbot_Agent
agents:
  lineshopbot_Agent:
    name: lineshopbot_Agent
    language: python
    node_version: null
    entrypoint: src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: src
    aws:
      execution_role: arn:aws:iam::179323781340:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-1-dff698f4cf
      execution_role_auto_create: false
      account: '179323781340'
      region: ap-northeast-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-179323781340-ap-northeast-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: lineshopbot_Agent-bO1T7aE4xR
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-1:179323781340:runtime/lineshopbot_Agent-bO1T7aE4xR
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
